### ISSUE TITLE
Cannot handle `OCI runtime create failed` as OnTransientError.

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#12793]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Ref: https://github.com/argoproj/argo-workflows/discussions/12769

### Current Status
We have started running Argo Workflows with EKS.
In rare cases, the workflow fails with the following error
```console
StartError (exit code 128): failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: unable to freeze: unknown
```
(this seems to be caused by containerd, so I won't mention it)
So we set TRANSIENT_ERROR_PATTERN to target `OCI runtime create failed` as OnTransientError.

```yaml
  templateDefaults:
    retryStrategy:
      limit: '10'
      retryPolicy: OnTransientError
      backoff:
        duration: '1'
        factor: '2'
        maxDuration: 1m
```

### Issue

Should have been retried, but wasn't.

![image](https://github.com/argoproj/argo-workflows/assets/4182311/8d6fd8b3-91b2-46f4-8d7e-8ee98ba833f0)

### Guess

I expected to see ["Transient error" or "Non-transient error" in the log](https://github.com/argoproj/argo-workflows/blob/5b3909b9567a5c6fc4fef81ac0785cfddbffb291/util/errors/errors.go#L41-L45), but nothing is output.
You may not have caught it with TRANSIENT_ERROR_PATTERN.

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
level=info msg="Processing workflow" Phase= ResourceVersion=390886707 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=info msg="Updated phase  -> Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Created PDB resource for workflow." namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="Node was nil, will be initialized as type Skipped" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Retry node eg-receive-monitoring-data-1710297000 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Pod node eg-receive-monitoring-data-1710297000-2109957022 initialized Pending" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Created pod: eg-receive-monitoring-data-1710297000(0) (eg-receive-monitoring-data-1710297000-main-2109957022)" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow update successful" namespace=production-workflow phase=Running resourceVersion=390886736 workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390886736 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-2109957022 old.message= old.phase=Pending old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow update successful" namespace=production-workflow phase=Running resourceVersion=390886968 workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390886968 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-2109957022 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390886968 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-2109957022 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390886968 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message= new.phase=Running new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-2109957022 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow update successful" namespace=production-workflow phase=Running resourceVersion=390889414 workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390889414 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message= new.phase=Succeeded new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-2109957022 old.message= old.phase=Running old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000 phase Running -> Succeeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000 finished: 2024-03-13 02:32:13.922495661 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Running OnExit handler: exit-handler" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Running OnExit handler: exit-handler" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="Node was nil, will be initialized as type Skipped" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Retry node eg-receive-monitoring-data-1710297000-3500983706 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Steps node eg-receive-monitoring-data-1710297000-1934510401 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="StepGroup node eg-receive-monitoring-data-1710297000-3409997669 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="Node was nil, will be initialized as type Skipped" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Retry node eg-receive-monitoring-data-1710297000-3942232621 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Steps node eg-receive-monitoring-data-1710297000-3427142780 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="StepGroup node eg-receive-monitoring-data-1710297000-2464599510 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="Node was nil, will be initialized as type Skipped" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Retry node eg-receive-monitoring-data-1710297000-3302502371 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Pod node eg-receive-monitoring-data-1710297000-910848174 initialized Pending" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Created pod: eg-receive-monitoring-data-1710297000.onExit(0)[0].datadog-metrics(0)[0].exit-status-count(0) (eg-receive-monitoring-data-1710297000-datadog-910848174)" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="Node was nil, will be initialized as type Skipped" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Retry node eg-receive-monitoring-data-1710297000-1647848193 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Pod node eg-receive-monitoring-data-1710297000-3371113560 initialized Pending" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Created pod: eg-receive-monitoring-data-1710297000.onExit(0)[0].datadog-metrics(0)[0].exit-duration-gauge(0) (eg-receive-monitoring-data-1710297000-datadog-3371113560)" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-2464599510 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="Node was nil, will be initialized as type Skipped" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Retry node eg-receive-monitoring-data-1710297000-2879126458 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Steps node eg-receive-monitoring-data-1710297000-1106096353 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="StepGroup node eg-receive-monitoring-data-1710297000-600262021 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="Node was nil, will be initialized as type Skipped" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Retry node eg-receive-monitoring-data-1710297000-207611301 initialized Running" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Pod node eg-receive-monitoring-data-1710297000-382804228 initialized Pending" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Created pod: eg-receive-monitoring-data-1710297000.onExit(0)[0].deadmans-snitch(0)[0].snitch-with-token(0) (eg-receive-monitoring-data-1710297000--382804228)" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Skipping eg-receive-monitoring-data-1710297000.onExit(0)[0].deadmans-snitch(0)[0].snitch-with-url: when ''none' != none' evaluated false" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Skipped node eg-receive-monitoring-data-1710297000-3787968001 initialized Skipped (message: when ''none' != none' evaluated false)" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-600262021 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Skipping eg-receive-monitoring-data-1710297000.onExit(0)[0].slack-notification: when 'false == true' evaluated false" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Skipped node eg-receive-monitoring-data-1710297000-1635476873 initialized Skipped (message: when 'false == true' evaluated false)" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-3409997669 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow update successful" namespace=production-workflow phase=Running resourceVersion=390889671 workflow=eg-receive-monitoring-data-1710297000
level=info msg="cleaning up pod" action=deletePod key=production-workflow/eg-receive-monitoring-data-1710297000-main-2109957022/deletePod
level=info msg="Processing workflow" Phase=Running ResourceVersion=390889671 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message= new.phase=Running new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-382804228 old.message= old.phase=Pending old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-910848174 old.message= old.phase=Pending old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-3371113560 old.message= old.phase=Pending old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Running OnExit handler: exit-handler" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-2464599510 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-600262021 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-3409997669 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow update successful" namespace=production-workflow phase=Running resourceVersion=390890014 workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390890014 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message= new.phase=Succeeded new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-382804228 old.message= old.phase=Running old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-910848174 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-3371113560 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Running OnExit handler: exit-handler" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-2464599510 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-207611301 phase Running -> Succeeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-207611301 finished: 2024-03-13 02:32:34.000432059 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Step group node eg-receive-monitoring-data-1710297000-600262021 successful" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-600262021 phase Running -> Succeeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-600262021 finished: 2024-03-13 02:32:34.000644381 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-207611301 is [eg-receive-monitoring-data-1710297000-382804228]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-3787968001 is [eg-receive-monitoring-data-1710297000-3787968001]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-1106096353 is [eg-receive-monitoring-data-1710297000-382804228 eg-receive-monitoring-data-1710297000-3787968001]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-1106096353 phase Running -> Succeeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-1106096353 finished: 2024-03-13 02:32:34.000735548 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-2879126458 phase Running -> Succeeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-2879126458 finished: 2024-03-13 02:32:34.001594006 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-3409997669 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow update successful" namespace=production-workflow phase=Running resourceVersion=390890247 workflow=eg-receive-monitoring-data-1710297000
level=info msg="cleaning up pod" action=deletePod key=production-workflow/eg-receive-monitoring-data-1710297000--382804228/deletePod
level=info msg="Processing workflow" Phase=Running ResourceVersion=390890247 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-3371113560 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-910848174 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Running OnExit handler: exit-handler" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-2464599510 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-3409997669 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390890247 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-3371113560 workflow=eg-receive-monitoring-data-1710297000
level=info msg="node unchanged" namespace=production-workflow nodeID=eg-receive-monitoring-data-1710297000-910848174 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Running OnExit handler: exit-handler" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-2464599510 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Workflow step group node eg-receive-monitoring-data-1710297000-3409997669 not yet completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Processing workflow" Phase=Running ResourceVersion=390890247 namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Task-result reconciliation" namespace=production-workflow numObjs=0 workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message= new.phase=Succeeded new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-3371113560 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="Pod failed: StartError (exit code 128): failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: unable to freeze: unknown" displayName="exit-status-count(0)" namespace=production-workflow pod=eg-receive-monitoring-data-1710297000-datadog-910848174 templateName=datadog workflow=eg-receive-monitoring-data-1710297000
level=info msg="node changed" namespace=production-workflow new.message="StartError (exit code 128): failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: unable to freeze: unknown" new.phase=Failed new.progress=0/1 nodeID=eg-receive-monitoring-data-1710297000-910848174 old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=eg-receive-monitoring-data-1710297000
level=info msg="TaskSet Reconciliation" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg=reconcileAgentPod namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Running OnExit handler: exit-handler" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Max duration limit exceeded. Failing..." namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3302502371 phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3302502371 message: Max duration limit exceeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3302502371 finished: 2024-03-13 02:34:05.065228153 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-1647848193 phase Running -> Succeeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-1647848193 finished: 2024-03-13 02:34:05.065793306 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Step group node eg-receive-monitoring-data-1710297000-2464599510 deemed failed: child 'eg-receive-monitoring-data-1710297000-3302502371' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-2464599510 phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-2464599510 message: child 'eg-receive-monitoring-data-1710297000-3302502371' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-2464599510 finished: 2024-03-13 02:34:05.065944547 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="step group eg-receive-monitoring-data-1710297000-2464599510 was unsuccessful: child 'eg-receive-monitoring-data-1710297000-3302502371' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-3302502371 is [eg-receive-monitoring-data-1710297000-910848174]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-1647848193 is [eg-receive-monitoring-data-1710297000-3371113560]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-3427142780 is [eg-receive-monitoring-data-1710297000-910848174 eg-receive-monitoring-data-1710297000-3371113560]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3427142780 phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3427142780 message: child 'eg-receive-monitoring-data-1710297000-3302502371' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3427142780 finished: 2024-03-13 02:34:05.066017662 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Max duration limit exceeded. Failing..." namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3942232621 phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3942232621 message: Max duration limit exceeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3942232621 finished: 2024-03-13 02:34:05.066538379 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Step group node eg-receive-monitoring-data-1710297000-3409997669 deemed failed: child 'eg-receive-monitoring-data-1710297000-3942232621' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3409997669 phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3409997669 message: child 'eg-receive-monitoring-data-1710297000-3942232621' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3409997669 finished: 2024-03-13 02:34:05.067164468 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="step group eg-receive-monitoring-data-1710297000-3409997669 was unsuccessful: child 'eg-receive-monitoring-data-1710297000-3942232621' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-3942232621 is [eg-receive-monitoring-data-1710297000-3427142780]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-2879126458 is [eg-receive-monitoring-data-1710297000-1106096353]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-1635476873 is [eg-receive-monitoring-data-1710297000-1635476873]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Outbound nodes of eg-receive-monitoring-data-1710297000-1934510401 is [eg-receive-monitoring-data-1710297000-3427142780 eg-receive-monitoring-data-1710297000-1106096353 eg-receive-monitoring-data-1710297000-1635476873]" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-1934510401 phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-1934510401 message: child 'eg-receive-monitoring-data-1710297000-3942232621' failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-1934510401 finished: 2024-03-13 02:34:05.067254146 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Max duration limit exceeded. Failing..." namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3500983706 phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3500983706 message: Max duration limit exceeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="node eg-receive-monitoring-data-1710297000-3500983706 finished: 2024-03-13 02:34:05.067729523 +0000 UTC" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Updated phase Running -> Failed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Updated message  -> Max duration limit exceeded" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Marking workflow completed" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Deleted PDB resource for workflow." namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="Marking workflow as pending archiving" namespace=production-workflow workflow=eg-receive-monitoring-data-1710297000
level=info msg="cleaning up pod" action=deletePod key=production-workflow/eg-receive-monitoring-data-1710297000-1340600742-agent/deletePod
level=info msg="Workflow update successful" namespace=production-workflow phase=Failed resourceVersion=390892918 workflow=eg-receive-monitoring-data-1710297000
level=info msg="archiving workflow" namespace=production-workflow uid=7eb0d165-4933-4ac4-93ff-a0f15e4b7c66 workflow=eg-receive-monitoring-data-1710297000
level=info msg="Queueing Failed workflow production-workflow/eg-receive-monitoring-data-1710297000 for delete in 5m0s due to TTL"
level=info msg="cleaning up pod" action=deletePod key=production-workflow/eg-receive-monitoring-data-1710297000-datadog-3371113560/deletePod
level=info msg="cleaning up pod" action=deletePod key=production-workflow/eg-receive-monitoring-data-1710297000-datadog-910848174/deletePod
level=info msg="Queueing Failed workflow production-workflow/eg-receive-monitoring-data-1710297000 for delete in 2m30s due to TTL"
level=info msg="Deleting garbage collected workflow 'production-workflow/eg-receive-monitoring-data-1710297000'"
level=info msg="Successfully request 'production-workflow/eg-receive-monitoring-data-1710297000' to be deleted"
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
> So we set TRANSIENT_ERROR_PATTERN to target `OCI runtime create failed` as OnTransientError.

Can you provide a snippet of your config like you did in #12769? The _exact_ string is important

> Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

I don't think this is "N/A". While the error is not easily reproducible, you should be able to simulate it or a similar error to reproduce the issue.

> I expected to see ["Transient error" or "Non-transient error" in the log](https://github.com/argoproj/argo-workflows/blob/5b3909b9567a5c6fc4fef81ac0785cfddbffb291/util/errors/errors.go#L41-L45), but nothing is output.

Yea that's surprising. I'm pretty confused how this could happen looking at the code. I would imagine it could happen if the node is not properly recorded, but it's showing up in the UI and with a message, so I would've thought it would've been evaluated.
It might be helpful if you could provide your completed Workflow resource so that the `status` can be analyzed.

Otherwise, maybe @Joibel has an idea how this could occur as he's worked on a few `retryPolicy` PRs.

**Comment by agilgur5** [comment]
> (this seems to be caused by containerd, so I won't mention it)

Btw, this same error message was [reported on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1708681280634989). I [suspected](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1708716462559279?thread_ts=1708681280.634989&cid=C01QW9QSSSK) a k8s node issue there and the user was able to solve it by updating(?) their AMI to newer Amazon Linux.
You might have a different root cause than them (especially if you're not using Amazon Linux), but the error is identical. I've also had similar errors due to bugs in Amazon Linux in the past

**Comment by panicboat** [comment]
Thanks for confirming.

> Can you provide a snippet of your config like you did in https://github.com/argoproj/argo-workflows/discussions/12769? The exact string is important

I used the string you taught me to set up.
(I tried a few others)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo
spec:
  template:
    spec:
      containers:
      - name: workflow-controller
        env:
        - name: TRANSIENT_ERROR_PATTERN
          value: ".*OCI runtime create failed.*"
```

> I don't think this is "N/A". While the error is not easily reproducible, you should be able to simulate it or a similar error to reproduce the issue.

This phenomenon occurred regardless of the workflow, so I have labeled it "N/A."
I am attaching the manifests after execution as an example.

[manifests.yaml.txt](https://github.com/argoproj/argo-workflows/files/14612120/manifests.yaml.txt)

**Comment by panicboat** [comment]
> Faulty k8s node is still a good use case for retryStrategy so would still be good to figure out why Argo didn't detect this, but you might be able to solve your root cause

I've learned some good things!
We too are EKS + Karpenter so will consider it!

**Comment by agilgur5** [comment]
> This phenomenon occurred regardless of the workflow, so I have labeled it "N/A."

In your environment it did, but I (and others) would not be able to reproduce this with any Workflow

> [manifests.yaml.txt](https://github.com/argoproj/argo-workflows/files/14612120/manifests.yaml.txt)

1. If you search for `OCI runtime create failed` in this completed Workflow, you'll get exactly one result from the `status` on node `eg-receive-monitoring-data-1710470400-2596637087`.
1. If you search that node ID, you'll see that it is listed under `children` of node `eg-receive-monitoring-data-1710470400-3380651252`.
    1. That parent is of `type: Retry`.
    1. It has a `message` that suggests what your root cause is: `Max duration limit exceeded`.

So your `retryStrategy` has hit its `maxDuration: 1m` and did not retry. This looks like intended behavior as such and not a bug.

**Comment by panicboat** [comment]
Thanks for confirming.
Am I correct in understanding that the logs don't output whether there was a retry or not, but in fact there was a retry?

**Comment by agilgur5** [comment]
More specifically, the portion of retry logic that logs "Transient error" or "Non-transient error" was not reached in this case, as the retry `node` hit its `maxDuration`.

Here's the code in `operator.go` that [checks for `maxDuration`](https://github.com/argoproj/argo-workflows/blob/2e5fb3b249535b0b92f36aa14caa059d5369ab61/workflow/controller/operator.go#L995). ~50 LoC below that is where [the `retryPolicy` is evaluated](https://github.com/argoproj/argo-workflows/blob/2e5fb3b249535b0b92f36aa14caa059d5369ab61/workflow/controller/operator.go#L1064). It returned before reaching that due to the `maxDuration` being hit.

**Comment by panicboat** [comment]
Thanks for the quick answer.
I think I understand!
Is it safe to leave this Issue as Open?

**Comment by agilgur5** [comment]
> Is it safe to leave this Issue as Open?

No, there is no bug here based on the root cause analysis [above](https://github.com/argoproj/argo-workflows/issues/12793#issuecomment-2007843362), that's why I changed the labels from `type/bug` to `type/support`.
If you extend your `maxDuration`, your `retryPolicy` should correctly capture this transient error (if you haven't solved the underlying `OCI runtime create failed` error [by updating your k8s node AMIs](https://github.com/argoproj/argo-workflows/issues/12793#issuecomment-1999010913) yet).

I believe I've also answered your further questions as to why that occurred and the order of which logging behaviors occur, so there does not seem to be any further action for this support issue.

**Comment by panicboat** [comment]
Thank you, I think I understand it all, so I will close this Issue.

**Comment by mrobinsonFS** [comment]
> > (this seems to be caused by containerd, so I won't mention it)
> 
> Btw, this same error message was [reported on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1708681280634989) a few weeks ago. I [suspected](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1708716462559279?thread_ts=1708681280.634989&cid=C01QW9QSSSK) a k8s node issue there and the user was able to solve it yesterday by updating(?) their AMI to newer Amazon Linux. You might have a different root cause than them (especially if you're not using Amazon Linux), but the error is identical. I've also had similar errors due to bugs in Amazon Linux in the past
> 
> Faulty k8s node is still a good use case for `retryStrategy` so would still be good to figure out why Argo didn't detect this, but you might be able to solve your root cause

I believe I have the same issue on my node. Could you possibly share which AMI this error occured on and what you upgraded to?

**Comment by agilgur5** [comment]
The linked Slack thread doesn't say which AMI it occurred on, but says it was resolved as such:
> fyi, we changed the amifamily to AL2023 and the issue is not happening anymore.

**Comment by panicboat** [comment]
I tried AL2023 but this did not solve this problem.

Is there enough configuration to catch this error as a Transient Error so I can retry?
I currently have the following settings.
```yaml
        env:
        - name: TRANSIENT_ERROR_PATTERN
          value: "(OCI runtime create failed|StartError)"
```

**Comment by fabioaraujopt** [comment]
https://github.com/argoproj/argo-workflows/pull/15183
