### ISSUE TITLE
Global output parameter reverts to its previous value after 2 seconds

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#1902]
The following workflow should simply set `global-parameter` to `initial`, then update it to `final`:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: overwrite-output-parameter-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:

    - - name: write-global-parameter
        template: global-parameter-generation
        arguments:
          parameters:
          - name: parameter
            value: initial

    - - name: consume-global-parameter-1
        template: global-parameter-consumption

    - - name: consume-global-parameter-2
        template: global-parameter-consumption

    - - name: overwrite-global-parameter
        template: nested-global-parameter-generation
        arguments:
          parameters:
          - name: parameter
            value: final

    - - name: consume-global-parameter-3
        template: global-parameter-consumption

    - - name: consume-global-parameter-4
        template: global-parameter-consumption

  - name: global-parameter-generation
    inputs:
      parameters:
      - name: parameter
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo '{{inputs.parameters.parameter}}' > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: parameter
        valueFrom:
          path: /tmp/hello_world.txt
        globalName: global-parameter

  - name: nested-global-parameter-generation
    inputs:
      parameters:
      - name: parameter
    steps:
    - - name: generate-parameter
        template: global-parameter-generation
        arguments:
          parameters:
          - name: parameter
            value: "{{inputs.parameters.parameter}}"

  - name: global-parameter-consumption
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{workflow.outputs.parameters.global-parameter}}"]
```

However, the parameter reverts to `initial` after about 2 seconds. We can observe this by `watch` (as global parameters are recorded there) or with the consume steps in the workflow. Here are the logs:
```
consume-global-parameter-1:     initial
consume-global-parameter-2:     initial
consume-global-parameter-3:     final
consume-global-parameter-4:     initial
```
As we can see, `consume-global-parameter-3` is able to start before the parameter is reverted, but `consume-global-parameter-4` is too late.

Most surprisingly, this bug only occurs with **this particular arrangement**: The global parameter must be initially set in a top-level template (`global-parameter-generation`) but then reset _within_ the `steps` of a nested template (`nested-global-parameter-generation`). If both writing steps use `global-parameter-generation` or `nested-global-parameter-generation`, or if the writing step uses `nested-global-parameter-generation` and the overwriting step uses `global-parameter-generation`, it works as expected:
```
consume-global-parameter-1:     initial
consume-global-parameter-2:     initial
consume-global-parameter-3:     final
consume-global-parameter-4:     final
```
I also tested whether the "depth" matters by adding a `very-nested-global-parameter-generation` step. It succeeded and failed in the same ways that `nested-global-parameter-generation` does, so it seems to only depend on whether the output parameter was most recently set from a top-level template or not (nested -> top-level -> nested causes the same error on the second update).

All of this is on Argo v2.4.3.

**Comment by samath117** [comment]
Any progress / hope on this? It's caused me a bunch of befuddling problems with global parameters, and appears to still be an issue as of v2.6.1.

**Comment by simster7** [comment]
@samath117 This should be fixed in the next release

**Comment by samath117** [comment]
@simster7 You mean v2.7.1? Because I checked and it's still an issue in v2.7.0.

**Comment by simster7** [comment]
HI @samath117, looks like fb74ba1ce27b96473411c2c5cfe9a86972af589e didn't actually get merged into the release branch when it should have. I have just merged it now.

We'll try to get v2.7.1 with this fix and others out on Monday.

**Comment by simster7** [comment]
@samath117 This is now released in 2.7.1: https://github.com/argoproj/argo/releases/tag/v2.7.1

**Comment by samath117** [comment]
Confirmed -- it's fixed! Thanks for all your work.
