### ISSUE TITLE
WorkflowFailed event not always firing

### ISSUE THREAD

**Issue by dan-katz** [argoproj/argo-workflows#4136]
## Summary 

Sometimes a WorkflowFailed kubernetes event doesn't fire after a Workflow fails. From my testing it happens when there are at least 12 steps in the Workflow.

## Diagnostics

v2.9.5

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-09-25T13:23:00Z"
  generateName: workflow-failed-event-not-firing-
  generation: 39
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
  name: workflow-failed-event-not-firing-smzs6
  namespace: default
  resourceVersion: "352835057"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflows/workflow-failed-event-not-firing-smzs6
  uid: 3ba0c4d2-ff32-11ea-ba59-42010a800066
spec:
  arguments: {}
  entrypoint: intentional-fail
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: intentional-fail
    outputs: {}
    steps:
    - - arguments: {}
        name: step-1
        template: succeed
    - - arguments: {}
        name: step-2
        template: succeed
    - - arguments: {}
        name: step-3
        template: succeed
    - - arguments: {}
        name: step-4
        template: succeed
    - - arguments: {}
        name: step-5
        template: succeed
    - - arguments: {}
        name: step-6
        template: succeed
    - - arguments: {}
        name: step-7
        template: succeed
    - - arguments: {}
        name: step-8
        template: succeed
    - - arguments: {}
        name: step-9
        template: succeed
    - - arguments: {}
        name: step-10
        template: succeed
    - - arguments: {}
        name: step-11
        template: succeed
    - - arguments: {}
        name: step-12
        template: fail
  - arguments: {}
    container:
      args:
      - echo succeed
      command:
      - sh
      - -c
      image: alpine:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: succeed
    outputs: {}
  - arguments: {}
    container:
      args:
      - echo fail; exit 1
      command:
      - sh
      - -c
      image: alpine:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: fail
    outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 1209600
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-09-25T13:23:50Z"
  message: child 'workflow-failed-event-not-firing-smzs6-4006210821' failed
  nodes:
    workflow-failed-event-not-firing-smzs6:
      children:
      - workflow-failed-event-not-firing-smzs6-1930865503
      displayName: workflow-failed-event-not-firing-smzs6
      finishedAt: "2020-09-25T13:23:50Z"
      id: workflow-failed-event-not-firing-smzs6
      message: child 'workflow-failed-event-not-firing-smzs6-4006210821' failed
      name: workflow-failed-event-not-firing-smzs6
      outboundNodes:
      - workflow-failed-event-not-firing-smzs6-4006210821
      phase: Failed
      startedAt: "2020-09-25T13:23:00Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Steps
    workflow-failed-event-not-firing-smzs6-599186725:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-1929585575
      displayName: step-8
      finishedAt: "2020-09-25T13:23:31Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-2wx3
      id: workflow-failed-event-not-firing-smzs6-599186725
      name: workflow-failed-event-not-firing-smzs6[7].step-8
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:29Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-1627935397:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3005324667
      displayName: step-4
      finishedAt: "2020-09-25T13:23:15Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-2wx3
      id: workflow-failed-event-not-firing-smzs6-1627935397
      name: workflow-failed-event-not-firing-smzs6[3].step-4
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:13Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-1769179407:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-1996843146
      displayName: step-9
      finishedAt: "2020-09-25T13:23:35Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-5q60
      id: workflow-failed-event-not-firing-smzs6-1769179407
      name: workflow-failed-event-not-firing-smzs6[8].step-9
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 2
        memory: 2
      startedAt: "2020-09-25T13:23:32Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-1929585575:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-1769179407
      displayName: '[8]'
      finishedAt: "2020-09-25T13:23:37Z"
      id: workflow-failed-event-not-firing-smzs6-1929585575
      name: workflow-failed-event-not-firing-smzs6[8]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:32Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-1930865503:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-2533456783
      displayName: '[0]'
      finishedAt: "2020-09-25T13:23:04Z"
      id: workflow-failed-event-not-firing-smzs6-1930865503
      name: workflow-failed-event-not-firing-smzs6[0]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:00Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-1931409956:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-1627935397
      displayName: '[3]'
      finishedAt: "2020-09-25T13:23:17Z"
      id: workflow-failed-event-not-firing-smzs6-1931409956
      name: workflow-failed-event-not-firing-smzs6[3]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:13Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-1931998336:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-599186725
      displayName: '[7]'
      finishedAt: "2020-09-25T13:23:32Z"
      id: workflow-failed-event-not-firing-smzs6-1931998336
      name: workflow-failed-event-not-firing-smzs6[7]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:29Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-1996843146:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3859179624
      displayName: '[9]'
      finishedAt: "2020-09-25T13:23:41Z"
      id: workflow-failed-event-not-firing-smzs6-1996843146
      name: workflow-failed-event-not-firing-smzs6[9]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:37Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-1998961717:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-2507067167
      displayName: '[6]'
      finishedAt: "2020-09-25T13:23:29Z"
      id: workflow-failed-event-not-firing-smzs6-1998961717
      name: workflow-failed-event-not-firing-smzs6[6]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:25Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-2101381695:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3072582238
      displayName: step-5
      finishedAt: "2020-09-25T13:23:20Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-2wx3
      id: workflow-failed-event-not-firing-smzs6-2101381695
      name: workflow-failed-event-not-firing-smzs6[4].step-5
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 2
        memory: 2
      startedAt: "2020-09-25T13:23:17Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-2401461729:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-1998961717
      displayName: step-6
      finishedAt: "2020-09-25T13:23:24Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-5q60
      id: workflow-failed-event-not-firing-smzs6-2401461729
      name: workflow-failed-event-not-firing-smzs6[5].step-6
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:22Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-2507067167:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-1931998336
      displayName: step-7
      finishedAt: "2020-09-25T13:23:27Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-5q60
      id: workflow-failed-event-not-firing-smzs6-2507067167
      name: workflow-failed-event-not-firing-smzs6[6].step-7
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:25Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-2533456783:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3071890690
      displayName: step-1
      finishedAt: "2020-09-25T13:23:02Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-2wx3
      id: workflow-failed-event-not-firing-smzs6-2533456783
      name: workflow-failed-event-not-firing-smzs6[0].step-1
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:00Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-2554087700:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3830738341
      displayName: '[10]'
      finishedAt: "2020-09-25T13:23:46Z"
      id: workflow-failed-event-not-firing-smzs6-2554087700
      name: workflow-failed-event-not-firing-smzs6[10]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:41Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-3005324667:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-2101381695
      displayName: '[4]'
      finishedAt: "2020-09-25T13:23:22Z"
      id: workflow-failed-event-not-firing-smzs6-3005324667
      name: workflow-failed-event-not-firing-smzs6[4]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:17Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-3071890690:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3215604585
      displayName: '[1]'
      finishedAt: "2020-09-25T13:23:08Z"
      id: workflow-failed-event-not-firing-smzs6-3071890690
      name: workflow-failed-event-not-firing-smzs6[1]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:04Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-3072037785:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3854397695
      displayName: '[2]'
      finishedAt: "2020-09-25T13:23:13Z"
      id: workflow-failed-event-not-firing-smzs6-3072037785
      name: workflow-failed-event-not-firing-smzs6[2]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:08Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-3072582238:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-2401461729
      displayName: '[5]'
      finishedAt: "2020-09-25T13:23:25Z"
      id: workflow-failed-event-not-firing-smzs6-3072582238
      name: workflow-failed-event-not-firing-smzs6[5]
      phase: Succeeded
      startedAt: "2020-09-25T13:23:22Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-3215604585:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3072037785
      displayName: step-2
      finishedAt: "2020-09-25T13:23:06Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-2wx3
      id: workflow-failed-event-not-firing-smzs6-3215604585
      name: workflow-failed-event-not-firing-smzs6[1].step-2
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:04Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-3694818697:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-4006210821
      displayName: '[11]'
      finishedAt: "2020-09-25T13:23:50Z"
      id: workflow-failed-event-not-firing-smzs6-3694818697
      message: child 'workflow-failed-event-not-firing-smzs6-4006210821' failed
      name: workflow-failed-event-not-firing-smzs6[11]
      phase: Failed
      startedAt: "2020-09-25T13:23:46Z"
      templateName: intentional-fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: StepGroup
    workflow-failed-event-not-firing-smzs6-3830738341:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-3694818697
      displayName: step-11
      finishedAt: "2020-09-25T13:23:44Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-5q60
      id: workflow-failed-event-not-firing-smzs6-3830738341
      name: workflow-failed-event-not-firing-smzs6[10].step-11
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 2
        memory: 2
      startedAt: "2020-09-25T13:23:41Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-3854397695:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-1931409956
      displayName: step-3
      finishedAt: "2020-09-25T13:23:11Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-2wx3
      id: workflow-failed-event-not-firing-smzs6-3854397695
      name: workflow-failed-event-not-firing-smzs6[2].step-3
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 2
        memory: 2
      startedAt: "2020-09-25T13:23:08Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-3859179624:
      boundaryID: workflow-failed-event-not-firing-smzs6
      children:
      - workflow-failed-event-not-firing-smzs6-2554087700
      displayName: step-10
      finishedAt: "2020-09-25T13:23:39Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-5q60
      id: workflow-failed-event-not-firing-smzs6-3859179624
      name: workflow-failed-event-not-firing-smzs6[9].step-10
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:37Z"
      templateName: succeed
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
    workflow-failed-event-not-firing-smzs6-4006210821:
      boundaryID: workflow-failed-event-not-firing-smzs6
      displayName: step-12
      finishedAt: "2020-09-25T13:23:48Z"
      hostNodeName: gke-monitron-cluster-pool-name-e5fa9ef5-5q60
      id: workflow-failed-event-not-firing-smzs6-4006210821
      message: failed with exit code 1
      name: workflow-failed-event-not-firing-smzs6[11].step-12
      outputs:
        exitCode: "1"
      phase: Failed
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-09-25T13:23:46Z"
      templateName: fail
      templateScope: local/workflow-failed-event-not-firing-smzs6
      type: Pod
  phase: Failed
  resourcesDuration:
    cpu: 16
    memory: 16
  startedAt: "2020-09-25T13:23:00Z" 
```

```
time="2020-09-25T13:23:00Z" level=info msg="Processing workflow" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:00Z" level=info msg="Updated phase  -> Running" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:00Z" level=info msg="Steps node workflow-failed-event-not-firing-smzs6 initialized Running" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:00Z" level=info msg="StepGroup node workflow-failed-event-not-firing-smzs6-1930865503 initialized Running" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:00Z" level=info msg="Pod node workflow-failed-event-not-firing-smzs6-2533456783 initialized Pending" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:00Z" level=info msg="Created pod: workflow-failed-event-not-firing-smzs6[0].step-1 (workflow-failed-event-not-firing-smzs6-2533456783)" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:00Z" level=info msg="Workflow step group node workflow-failed-event-not-firing-smzs6-1930865503 not yet completed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:00Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=352834570 workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:01Z" level=info msg="Processing workflow" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:01Z" level=info msg="Updating node workflow-failed-event-not-firing-smzs6-2533456783 message: ContainerCreating"
time="2020-09-25T13:23:01Z" level=info msg="Skipped pod workflow-failed-event-not-firing-smzs6[0].step-1 (workflow-failed-event-not-firing-smzs6-2533456783) creation: already exists" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:01Z" level=info msg="Workflow step group node workflow-failed-event-not-firing-smzs6-1930865503 not yet completed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:01Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=352834576 workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:02Z" level=info msg="Processing workflow" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:02Z" level=info msg="Updating node workflow-failed-event-not-firing-smzs6-2533456783 status Pending -> Running"
time="2020-09-25T13:23:02Z" level=info msg="Workflow step group node workflow-failed-event-not-firing-smzs6-1930865503 not yet completed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:02Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=352834582 workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:02Z" level=info msg="insignificant pod change" key=default/workflow-failed-event-not-firing-smzs6-2533456783
time="2020-09-25T13:23:03Z" level=info msg="Processing workflow" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:03Z" level=info msg="Setting node workflow-failed-event-not-firing-smzs6-2533456783 outputs"
ring-smzs6-3215604585 are [workflow-failed-event-not-firing-smzs6-3215604585]" namespace=default workflow=workflow-failed-event-not-firing-smzs6

<-- More of the same -->

time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6-1996843146 phase Running -> Succeeded" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6-2554087700 phase Succeeded -> Running" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="SG Outbound nodes of workflow-failed-event-not-firing-smzs6-3859179624 are [workflow-failed-event-not-firing-smzs6-3859179624]" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Step group node &NodeStatus{ID:workflow-failed-event-not-firing-smzs6-2554087700,Name:workflow-failed-event-not-firing-smzs6[10],DisplayName:[10],Type:StepGroup,TemplateName:intentional-fail,TemplateRef:nil,Phase:Running,BoundaryID:workflow-failed-event-not-firing-smzs6,Message:,StartedAt:2020-09-25 13:23:41 +0000 UTC,FinishedAt:2020-09-25 13:23:46 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[workflow-failed-event-not-firing-smzs6-3830738341],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:local/workflow-failed-event-not-firing-smzs6,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6-2554087700 phase Running -> Succeeded" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="SG Outbound nodes of workflow-failed-event-not-firing-smzs6-3830738341 are [workflow-failed-event-not-firing-smzs6-3830738341]" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Step group node workflow-failed-event-not-firing-smzs6-3694818697 deemed failed: child 'workflow-failed-event-not-firing-smzs6-4006210821' failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6-3694818697 phase Running -> Failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6-3694818697 message: child 'workflow-failed-event-not-firing-smzs6-4006210821' failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6-3694818697 finished: 2020-09-25 13:23:50.655517019 +0000 UTC" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="step group workflow-failed-event-not-firing-smzs6-3694818697 was unsuccessful: child 'workflow-failed-event-not-firing-smzs6-4006210821' failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Outbound nodes of workflow-failed-event-not-firing-smzs6-4006210821 is [workflow-failed-event-not-firing-smzs6-4006210821]" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Outbound nodes of workflow-failed-event-not-firing-smzs6 is [workflow-failed-event-not-firing-smzs6-4006210821]" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6 phase Running -> Failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6 message: child 'workflow-failed-event-not-firing-smzs6-4006210821' failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="node workflow-failed-event-not-firing-smzs6 finished: 2020-09-25 13:23:50.656521035 +0000 UTC" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Checking daemoned children of workflow-failed-event-not-firing-smzs6" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Updated phase Running -> Failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Updated message  -> child 'workflow-failed-event-not-firing-smzs6-4006210821' failed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Marking workflow completed" namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Checking daemoned children of " namespace=default workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:50Z" level=info msg="Workflow update successful" namespace=default phase=Failed resourceVersion=352835057 workflow=workflow-failed-event-not-firing-smzs6
time="2020-09-25T13:23:51Z" level=info msg="Labeled pod default/workflow-failed-event-not-firing-smzs6-4006210821 completed"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
It works for me. But Kubernetes events are best efforts to deliver not guaranteed. It may miss if API server is to busy with some other works.

https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver/

```
78s         Normal    WorkflowRunning             workflow/workflow-failed-event-not-firing-6mcwz                     Workflow Running
72s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[0].step-1
72s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[0]
67s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[1].step-2
67s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[1]
62s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[2].step-3
62s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[2]
57s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[3].step-4
57s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[3]
52s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[4].step-5
52s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[4]
46s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[5].step-6
46s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[5]
41s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[6].step-7
12s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     (combined from similar events): Succeeded node workflow-failed-event-not-firing-6mcwz[10]
29s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[8].step-9
29s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[8]
22s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[9].step-10
22s         Normal    WorkflowNodeSucceeded       workflow/workflow-failed-event-not-firing-6mcwz                     Succeeded node workflow-failed-event-not-firing-6mcwz[9]
2s          Warning   WorkflowNodeFailed          workflow/workflow-failed-event-not-firing-6mcwz                     Failed node workflow-failed-event-not-firing-6mcwz[11].step-12: failed with exit code 1
2s          Warning   WorkflowNodeFailed          workflow/workflow-failed-event-not-firing-6mcwz                     Failed node workflow-failed-event-not-firing-6mcwz[11]: child 'workflow-failed-event-not-firing-6mcwz-1092389557' failed
2s          Warning   WorkflowNodeFailed          workflow/workflow-failed-event-not-firing-6mcwz                     Failed node workflow-failed-event-not-firing-6mcwz: child 'workflow-failed-event-not-firing-6mcwz-1092389557' failed
2s          Warning   WorkflowFailed              workflow/workflow-failed-event-not-firing-6mcwz                     child 'workflow-failed-event-not-firing-6mcwz-1092389557' failed

```

**Comment by alexec** [comment]
@dan-katz some thoughts:

* It is unclear if you are able to reliably reproduce this. Does it always happen? Only sometimes happen?
* The firing of events is logged at `--loglevel=debug`. If you're able to reproduce this, those logs might give more insights.

**Comment by AntoineDao** [comment]
We are experiencing a similar issue trying to scrape workflow events for post-processing. I think scraping workflow events from Kubernetes events might not be the right way to reliably access them. As @sarabala1979 was saying above Kubernetes events are "best-effort" and on top of that I think they are compressed/ignored by Kubernetes to avoid overloading etcd (which is why we get the `combined from similar events`).

I am also noticing that once I start getting `combined from similar events` strings added to the `WorkflowNodeSucceeded` events I will then not reliably receive other types of events such as `WorkflowSucceeded`. I am not sure what logs you refer to being logged at `debug` level but I have found that all the node/workflow updates are properly persisted to `info` which I why I suspect that the events not being picked up using kubectl is mostly down to Kubernetes rate limiting rather than Argo not firing them in the first place.

Is there a consensus on best practices to persist workflow events reliably?

**Comment by alexec** [comment]
@AntoineDao I'm not an expert in K8S events, but I do know that there was a bug fixed in v2.11. I think you're already running this version?

I think you should reasonably expect to get all events - if not I think it is a bug.

**Comment by AntoineDao** [comment]
I'm currently running from this commit: 3aeb1741e720a7e7e005321451b2701f263ed85a so I should have the bug fixed in 2.11 in there but I am still not receiving all the events reliably. Guess it's getting labelled as a bug then 😅

**Comment by alexec** [comment]
@AntoineDao we're busy with KubeCon this week. Maybe you could help by tracking down the logic in the Kubernetes codebase to see how it determine to combine similar events?

https://github.com/kubernetes/kubernetes/blob/c23a4b08d704156db724769a32edc71c921095d4/staging/src/k8s.io/client-go/tools/record/events_cache.go#L179

**Comment by kennytrytek** [comment]
After encountering similar behavior as what is described by this bug in Argo 3.1.1, I started looking through the Kubernetes source to see how it decides to aggregate events, and found this:
https://github.com/kubernetes/kubernetes/blob/c23a4b08d704156db724769a32edc71c921095d4/staging/src/k8s.io/client-go/tools/record/events_cache.go#L417-L447
```
// The default behavior is as follows:
//   * Aggregation is performed if a similar event is recorded 10 times in a
//     in a 10 minute rolling interval.  A similar event is an event that varies only by
//     the Event.Message field.  Rather than recording the precise event, aggregation
//     will create a new event whose message reports that it has combined events with
//     the same reason.
```
If that docstring is accurate, it should be expected that 10+ `WorkflowNodeSucceeded` events happening in under ten minutes will be aggregated together since they only differ in the Message field. This appears to be what the original report was describing (12 steps in the workflow).

I believe this issue should be reopened, or a new one filed for this behavior. I would be interested in finding a solution for this issue, as well as creating a workflow that can reliably reproduce it; it should be fairly simple to make a workflow with many nodes that complete quickly.
