### ISSUE TITLE
SSO "authorization" cookie seems to be set incorrectly, causing a "token not valid for running mode" error

### ISSUE THREAD

**Issue by Himself12794** [argoproj/argo-workflows#5916]
## Summary 
I've set up my installation of Argo following the documentation at [Argo Server SSO](https://argoproj.github.io/argo-workflows/argo-server-sso/). RBAC additionally has been set up.

Based on the server logs, I can see that my token is successfully being fetched, and the `sso` secret is being created. When trying to access the UI resources however, I'm experiencing the `token not valid for running mode` error. Inspecting the request and taking a look at my cookies, I noticed that the authorization cookie seems to be surrounded by quotations, showing up in the developer tools as:
```
...
authorization: "\"Bearer v2:aFakeDemoToken\""
cdcSsoTimer: "LoggedIn"
...
```
Instead of the expected:
```
...
authorization: "Bearer v2:aFakeDemoToken"
cdcSsoTimer: "LoggedIn"
...
```
When I took that authorization value and stripped the extra quotes, I was able to make successful API calls.
I experienced this issue in both Chrome and Firefox.

## Diagnostics

What Kubernetes provider are you using? 
```
Kubernetes Version: 1.20
```

What version of Argo Workflows are you running? 
```
version="{v3.0.2 2021-04-20T14:52:16Z 38fff9c0e0f04663b0ee1e44ae0a3183bed6561d v3.0.2 clean go1.15.7 gc linux/amd64}"
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by alexec** [comment]
This is fixed in v3.1. Can you please test with v3.1.0-rc3

**Comment by Himself12794** [comment]
I was able to upgrade to v3.1.0-rc3 and test this, unfortunately I still experienced the same issue even after opening it in a private browser.

**Comment by alexec** [comment]
> I was able to upgrade to v3.1.0-rc3 and test this, unfortunately I still experienced the same issue even after opening it in a private browser.

Make sure you clear your cache?

**Comment by Himself12794** [comment]
> 
> 
> > I was able to upgrade to v3.1.0-rc3 and test this, unfortunately I still experienced the same issue even after opening it in a private browser.
> 
> Make sure you clear your cache?

I did; cleared the cache, opened in a private session, and even deleted the sso secret for good measure. I can take another crack at it today, maybe my last attempt was a fluke.

**Comment by Himself12794** [comment]
@alexec, not sure why it wasn't working for me on Friday, but I can confirm that it now works correctly, thanks for the support!
