### ISSUE TITLE
workflow fail if loop param results are skipped even if not used

### ISSUE THREAD

**Issue by yoandl** [argoproj/argo-workflows#7094]
## Summary

when you create a workflow with "withParam" provided by a previous steps, if you skip both steps, the workflow fail instantly with this error : 

```
withParam value could not be parsed as a JSON list: {{steps.generate.outputs.result}}: invalid character '{' looking for beginning of object key string
```

Argo workflow version 3.2.2, 3.3.3 

## Diagnostics
execute this workflow with `get-list` set to  "false" 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  arguments:
    parameters:
      - name: get-list
        value: true
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        when: "{{ workflow.parameters.get-list}} == true"
        template: gen-number-list
    - - name: sleep
        when: "{{ workflow.parameters.get-list}} == true" 
        
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}"
    - - name: sleep-2
        template: sleep-n-sec
        arguments:
          parameters:
          - name: seconds
            value: "5"

  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(20, 31)], sys.stdout)
  - name: sleep-n-sec
    inputs:
      parameters:
      - name: seconds
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for {{inputs.parameters.seconds}} seconds; sleep {{inputs.parameters.seconds}}; echo done"]

```

What Kubernetes provider are you using?
1.18
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
k8s eks on aws

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ziv-codefresh** [comment]
I have checked this issue and i found that the origin of this error is in `expandStep`/`expandTask` functions. 
the following line is failed because the value of `step.WithParam` field is not evaluated, so the actual value is `{{steps.generate.outputs.result}}` and not a valid JSON list.

to avoid this issue we can check if the value of `step.WithParam` is not an template by the following condition: 
`if !strings.HasPrefix(step.WithParam, "{{") || !strings.HasSuffix(step.WithParam, "}}")`

from quick check i see that this solution is works as expected and the error is not being thrown, the steps are being skipped and the workflow finish successfully.

@alexec @sarabala1979 if you can assign it to me ill submit a pr with the required tests.

**Comment by alexec** [comment]
done

**Comment by sarabala1979** [comment]
@ziv-codefresh it should fix in `ProcessArgs` if any variable is not resolved or substituted, it should take the default value.
it default value is not configured, workflow should fail with `not supplied`
