### ISSUE TITLE
containers in containersets not appropriately reporting status if terminated

### ISSUE THREAD

**Issue by jeszii** [argoproj/argo-workflows#8545]
## Checklist
* [X] Double-checked my configuration.
* [X] Tested using the latest version.
* [X] Used the Emissary executor.

## Summary
What happened/what you expected to happen?
When terminating a workflow due to a deadline, I expect that the workflow is terminated, yet we are still waiting for containerset containers to be terminated, even though they are finished with error in k8s.

An image of the workflow after timeout termination:
<img width="1708" alt="Screen Shot 2022-04-29 at 7 05 21 PM" src="https://user-images.githubusercontent.com/104646655/165999047-491b87e6-5b41-4409-beb9-8bdc918ed776.png">

An image of the containers for shard-13 in k8s:
<img width="851" alt="Screen Shot 2022-04-29 at 7 07 00 PM" src="https://user-images.githubusercontent.com/104646655/165999314-81a01e30-5c88-4d62-a1cc-c2b4dff48c92.png">

What version are you running?
3.3.2

# Reproducible Workflow
[reproducible-workflow.txt](https://github.com/argoproj/argo-workflows/files/8592860/reproducible-workflow.txt)

# Logs from the workflow controller:
[controller-logs.txt](https://github.com/argoproj/argo-workflows/files/8592827/controller-logs.txt)

# The workflow's pods that are problematic:
```apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

# Logs from in your workflow's wait container:
[wait-logs.txt](https://github.com/argoproj/argo-workflows/files/8592829/wait-logs.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think this might be fixed by #8478. Could you please try `:latest`?

**Comment by jeszii** [comment]
Hi @alexec, thanks for the swift reply. :D 
Can you elaborate on what needs to be upgraded to latest?

I had a colleague run the workflow on a fresh argo set up [using this manifest](https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml) and the problem seems to persist.

**Comment by alexec** [comment]
You need to upgrade the workflow-controller. Can you double check? It's pretty easy to apply the wrong manifests.

**Comment by jeszii** [comment]
I can double check but it won't be until next week, sorry! I have attached the workflow that reproduces the error if you'd like to run it beforehand though.

**Comment by cwood-uk** [comment]
We have built argo locally off the master branch and ran the attached workflow, we are still seeing the same errors
![Screenshot 2022-05-03 at 10 27 45](https://user-images.githubusercontent.com/102071543/166431935-f0796139-7883-4924-817f-0b7038604be2.png)

**Comment by jeszii** [comment]
thanks @cwood-uk

**Comment by alexec** [comment]
This issue is missing workflow YAML to run locally.

**Comment by jeszii** [comment]
@alexec The YAML is the reproducible-workflow.txt attached in the issue, Github doesn't allow the upload of YAML files. Have attached here again. :) 
[reproducible-workflow.txt](https://github.com/argoproj/argo-workflows/files/8612006/reproducible-workflow.txt)

**Comment by alexec** [comment]
Thank you. Can repro locally.

**Comment by alexec** [comment]
Pods do complete correctly. The workflow status is not being updated. This points to a problem it the controller. E.g. in operator.go

**Comment by alexec** [comment]
Worklow stops reconciling, but is not labelled completed.

**Comment by alexec** [comment]
Hypothesis: Pods are being labelled as complete, before the node status has been update.

**Comment by alexec** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: masscan-dummy-scan
spec:
  entrypoint: run-plugin
  activeDeadlineSeconds: 20
  arguments:
    parameters:
      - name: plugin
        value: "masscan"
  templates:
    - name: run-plugin
      dag:
        tasks:
          - name: shard-1
            template: run-masscan
          - name: shard-2
            template: run-masscan
          - name: shard-3
            template: run-masscan
          - name: shard-4
            template: run-masscan
          - name: shard-5
            template: run-masscan
          - name: shard-6
            template: run-masscan
          - name: shard-7
            template: run-masscan
          - name: shard-8
            template: run-masscan
          - name: shard-9
            template: run-masscan
          - name: shard-10
            template: run-masscan
    - name: run-masscan
      containerSet:
        containers:
          - name: a
            image: "debian:9.5-slim"
            command:
              - sleep
            args:
              - "10"
          - name: b
            image: "debian:9.5-slim"
            command:
              - sleep
            args:
              - "80"
            dependencies:
              - a
          - name: c
            image: "debian:9.5-slim"
            command:
              - sleep
            args:
              - "30"
            dependencies:
              - b
```

Simpler. Faster.

**Comment by alexec** [comment]
This is caused by `exec_control.go` deleting pods. Instead, lets terminate them.

**Comment by jeszii** [comment]
Thanks for all your work on this, let me know if you need any help from us.

**Comment by jeszii** [comment]
Hey @alexec, I noticed this was cherry picked for 3.3.6 so I upgraded, but I still seem to be getting the same issues where the workflow is still running after 'termination'. Am I right in thinking this was fixed in 3.3.6 or have I jumped the gun?
<img width="1792" alt="Screen Shot 2022-06-14 at 11 55 16 AM" src="https://user-images.githubusercontent.com/104646655/173561608-a362d433-2f82-4774-be8c-007e31dec9df.png">

**Comment by jeszii** [comment]
Hey @sarabala1979, can you confirm whether this has been merged into the :latest tag? Right now I am still getting the same errors.
<img width="1711" alt="Screen Shot 2022-06-22 at 10 41 22 AM" src="https://user-images.githubusercontent.com/104646655/174997935-10487167-c6fb-4c18-a48f-2880c0b730cb.png">

**Comment by the1schwartz** [comment]
![Screenshot 2022-09-20 at 10 11 47](https://user-images.githubusercontent.com/10114102/191204129-450200ee-453d-4b7a-80e9-aa7f846e71c0.png)

I can still reproduce this is 3.3.9.

**Comment by jeszii** [comment]
@the1schwartz @alexec I can also still reproduce this in 3.4.0 

<img width="1790" alt="Screen Shot 2022-09-20 at 1 16 55 PM" src="https://user-images.githubusercontent.com/104646655/191255865-0462f9a8-73a0-42f5-b772-78be863c84d2.png">
